name: Build and Push Docker container

on: 
  push:
    branches:
      - main
      - test

env:  
  containertag: ghcr.io/rajbos/local-dependency-updates
  containerhost: https://ghcr.io

jobs:
  build-and-push-main:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v1

    - name: PS Lint
      if: ${{ true }}  # enable for now
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        failOnWarnings: false
        settingsPath: /src/PSSASettings.psd1

    - name: Run Snyk to check Docker image for vulnerabilities
      if: ${{ false }}  # disable for now
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:      
        #todo: use env var if possible
        image: Dockerfile

    - name: Build the Docker image
      run: docker build -t $containertag .

    - name: Setup GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login $containerhost -u ${{ github.actor }} --password-stdin

    - name: Push to GitHub Container Registry
      run:  docker push $containertag
    
    - name: Cleanup GitHub Container Registry login data
      run: docker logout $containerhost



  build-and-push-branch:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v1

    - name: PS Lint
      if: ${{ true }}  # enable for now
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        failOnWarnings: false
        settingsPath: /src/PSSASettings.psd1

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master      
      if: ${{ false }}  # disable for now
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        CONTAINER_TAG: $containertag:${GITHUB_REF##*/}
      with:
        #todo: use env var if possible
        image: ghcr.io/rajbos/local-dependency-updates:test

    - name: Build the Docker image
      run: docker build -t $containertag:${GITHUB_REF##*/} .

    - name: Setup GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login $containerhost -u ${{ github.actor }} --password-stdin

    - name: Push to GitHub Container Registry
      run:  docker push $containertag:${GITHUB_REF##*/}

    - name: Cleanup GitHub Container Registry login data
      run: docker logout $containerhost